# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takemehome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_takemehome',
            name='date_departure',
        ),
        migrations.RemoveField(
            model_name='trip_takemehome',
            name='date_return',
        ),
        migrations.AddField(
            model_name='trip_takemehome',
            name='max_budget',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='trip_takemehome',
            name='start_week_day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=4, max_length=1),
        ),
    ]
