# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takemehome', '0002_auto_20170109_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_takemehome',
            name='number_of_bank_holidays',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='trip_takemehome',
            name='number_of_months_ahead',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
