# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 22:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takemehome', '0004_auto_20170110_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptakemehome',
            name='minimum_stay_days',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='triptakemehome',
            name='start_week_day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=4, max_length=1),
        ),
    ]
