# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('takemehome', '0005_auto_20170110_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDeparture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('flightname', models.CharField(default='NA', max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('flightname', models.CharField(default='NA', max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('time', models.DateTimeField()),
                ('flightdeparture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightsReturn', to='takemehome.FlightDeparture')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='triptakemehome',
            name='date_departure',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='triptakemehome',
            name='date_return',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='triptakemehome',
            name='one_way',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timecheck',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timechecks', to='takemehome.TripTakeMeHome'),
        ),
        migrations.AddField(
            model_name='flightdeparture',
            name='timecheck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightsDeparture', to='takemehome.TimeCheck'),
        ),
    ]
