# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_timeseries_pricepointids'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
