# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trip_oneway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='oneWay',
            new_name='one_way',
        ),
    ]
