# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170105_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepoint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
