# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trip_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
