# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170106_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepoint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 0, 27, 5, 452982, tzinfo=utc)),
        ),
    ]
