# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170106_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepoint',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
