# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170106_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='isreturn',
            field=models.BooleanField(default=False),
        ),
    ]
